name: did_change_authlocal
description: >-
  A Flutter plugin to detect biometric data changes (Face ID, Touch ID,
  Fingerprint). Protects against unauthorized biometric enrollment.
version: 1.0.0
repository: https://github.com/thongvo109/did_change_biometric
issues: https://github.com/thongvo109/did_change_biometric/issues
homepage: https://thongvo109.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.did_change_authlocal
        pluginClass: DidChangeAuthlocalPlugin
      ios:
        pluginClass: DidChangeAuthlocalPlugin
